baseURL = "https://ttymayor.com/"
languageCode = 'zh-tw'
title = '市長 / tantuyu'
theme = 'hugo-noir'

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
name = "市長 / tantuyu"
location = "New Taipei City, Taiwan"
description = "我好愛資訊"
profile_image = "/images/headshot.jpg"
discord = "tantuyutty"
github = "https://github.com/ttymayor"
twitter = "https://twitter.com/ttymayor"
instagram = "https://instagram.com/ttymayor.dev"
# email = "your.email@example.com"
# medium = "https://medium.com/@yourusername"
# linkedin = "https://linkedin.com/in/yourusername"

# 技術欄
[[params.techsRow1]]
  name = "Python"
  icon = "devicon-python-plain text-2xl"
[[params.techsRow1]]
  name = "C++"
  icon = "devicon-cplusplus-plain text-2xl"
[[params.techsRow1]]
  name = "MySQL"
  icon = "devicon-mysql-plain text-2xl"
[[params.techsRow1]]
  name = "Docker"
  icon = "devicon-docker-plain text-2xl"
[[params.techsRow1]]
  name = "Ubuntu"
  icon = "devicon-ubuntu-plain text-2xl"


[[params.techsRow2]]
  name = "Git"
  icon = "devicon-git-plain text-2xl"
[[params.techsRow2]]
  name = "VS Code"
  icon = "devicon-visualstudio-plain text-2xl"
[[params.techsRow2]]
  name = "Bash"
  icon = "devicon-bash-plain text-2xl"
[[params.techsRow2]]
  name = "GitHub"
  icon = "devicon-github-plain text-2xl"
[[params.techsRow2]]
  name = "Markdown"
  icon = "devicon-markdown-plain text-2xl"




# # 工作經驗模板
# [[params.experience]]
# company = "Company One"
# role = "Senior Role"
# period = "Jan 2023 - Present"
# logo = "/images/company/company1.png"
# description = "Brief description of your role and responsibilities."
# responsibilities = [
#     "Key responsibility with specific achievement",
#     "Key responsibility with specific achievement",
#     "Key responsibility with specific achievement",
#     "Key responsibility with specific achievement"
# ]

# # 作品集模板
# [[params.projects]]
#     title = "Project One"
#     description = "Brief description of the project and what it does."
#     tech = "Technologies used (e.g., Python, React, TensorFlow)"
#     image = "/images/projects/project1.png"
#     link = "https://github.com/yourusername/project1"

# # 部落格文章模板
# [[params.blogs]]
#     title = "Blog Post One"
#     date = "2023-03-01"
#     summary = "Brief summary of what the blog post is about."
#     tags = ["Tag1", "Tag2", "Tag3"]
#     content = """
#     Short excerpt or introduction to the blog post...
#     """
#     link = "https://yourblog.com/post1"

# # 活動經驗模板
# [[params.voluntary]]
# role = "Volunteer"
# organization = "Organization Name"
# period = "2020 - Present"
# description = "Brief description of your volunteer work and responsibilities."


[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  # [[menu.main]]
  #   name = "Experience"
  #   url = "/experience/"
  #   weight = 2
  # [[menu.main]]
  #   name = "Projects"
  #   url = "/projects/"
  #   weight = 3
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

