baseURL = "https://ttymayor.com/"
defaultContentLanguage = "zh-tw"
languageCode = 'zh-tw'
title = '市長 / tantuyu'
theme = 'hugo-noir'

# URL handling
relativeURLs = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        title = true

[params]
name = "市長 / tantuyu"
location = "New Taipei City, Taiwan"
description = "熱愛資訊的學生，正在學習後端開發中。"
profile_image = "/images/headshot.jpg"
discord = "tantuyutty"
github = "https://github.com/ttymayor"
github_username = "ttymayor"
twitter = "https://twitter.com/ttymayor"
instagram = "https://instagram.com/ttymayor.dev"
instagram_username = "ttymayor.dev"
email = "me@ttymayor.com"
# medium = "https://medium.com/@yourusername"
# linkedin = "https://linkedin.com/in/yourusername"
leetcode = "https://leetcode.com/xvwsb2p/"
leetcode_username = "ttymayor"

# 技術欄
[[params.techsRow1]]
  name = "Python"
  icon = "devicon-python-plain text-2xl"
[[params.techsRow1]]
  name = "C++"
  icon = "devicon-cplusplus-plain text-2xl"
[[params.techsRow1]]
  name = "MySQL"
  icon = "devicon-mysql-plain text-2xl"
[[params.techsRow1]]
  name = "Docker"
  icon = "devicon-docker-plain text-2xl"
[[params.techsRow1]]
  name = "Ubuntu"
  icon = "devicon-ubuntu-plain text-2xl"


[[params.techsRow2]]
  name = "Git"
  icon = "devicon-git-plain text-2xl"
[[params.techsRow2]]
  name = "VS Code"
  icon = "devicon-visualstudio-plain text-2xl"
[[params.techsRow2]]
  name = "Bash"
  icon = "devicon-bash-plain text-2xl"
[[params.techsRow2]]
  name = "GitHub"
  icon = "devicon-github-plain text-2xl"
[[params.techsRow2]]
  name = "Markdown"
  icon = "devicon-markdown-plain text-2xl"




# # 工作經驗模板
# [[params.experience]]
# company = "Company One"
# role = "Senior Role"
# period = "Jan 2023 - Present"
# logo = "/images/company/company1.png"
# description = "Brief description of your role and responsibilities."
# responsibilities = [
#     "Key responsibility with specific achievement",
#     "Key responsibility with specific achievement",
#     "Key responsibility with specific achievement",
#     "Key responsibility with specific achievement"
# ]

# # 作品集模板
# [[params.projects]]
#     title = "Project One"
#     description = "Brief description of the project and what it does."
#     tech = "Technologies used (e.g., Python, React, TensorFlow)"
#     image = "/images/projects/project1.png"
#     link = "https://github.com/yourusername/project1"

# # 部落格文章模板
# [[params.blogs]]
#     title = "Blog Post One"
#     date = "2023-03-01"
#     summary = "Brief summary of what the blog post is about."
#     tags = ["Tag1", "Tag2", "Tag3"]
#     content = """
#     Short excerpt or introduction to the blog post...
#     """
#     link = "https://yourblog.com/post1"

# 活動經驗模板
[[params.voluntary]]
organization = "SITCON 學生計算機年會"
role = "Attendee"
period = "2022, 2024, 2025"
[[params.voluntary]]
organization = "THU Hacker Club"
role = "Member"
period = "2024-09 - Present"

# 證書檢定模板
[[params.certifications]]
title = "APCS"
score = "觀念 4, 實作 3"
date = "2023-06"
[[params.certifications]]
title = "CPE"
score = "3 題"
date = "2025-03"


[menu]
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 1
  # [[menu.main]]
  #   name = "experience"
  #   url = "/experience/"
  #   weight = 2
  # [[menu.main]]
  #   name = "projects"
  #   url = "/projects/"
  #   weight = 3
  [[menu.main]]
    name = "blogs"
    url = "/blogs/"
    weight = 4
  [[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = 5
  # [[menu.main]]
  #   name = "posts"
  #   url = "/posts/"